// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Roulette.Infrastructure.Data;

#nullable disable

namespace Roulette.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RouletteDbContext))]
    [Migration("20251021230548_FixPasswordHash")]
    partial class FixPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Roulette.Domain.Entities.BetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("BetType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GamblerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("RouletteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Winnings")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GamblerId");

                    b.HasIndex("RouletteId");

                    b.ToTable("Bet", (string)null);
                });

            modelBuilder.Entity("Roulette.Domain.Entities.RouletteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorWinner")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberWinner")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roulette", (string)null);
                });

            modelBuilder.Entity("Roulette.Domain.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Roulette.Domain.Entities.CrupierEntity", b =>
                {
                    b.HasBaseType("Roulette.Domain.Entities.UserEntity");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.ToTable("Crupier", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Username = "crupier1",
                            Password = "$2a$11$erlnEHHme/pAaVi9IR9QMedGTFrV/9ajOsiycj2ejpRIRd04U8A0q"
                        });
                });

            modelBuilder.Entity("Roulette.Domain.Entities.GamblerEntity", b =>
                {
                    b.HasBaseType("Roulette.Domain.Entities.UserEntity");

                    b.Property<decimal>("Credit")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.ToTable("Gambler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Username = "user0",
                            Credit = 1000m
                        },
                        new
                        {
                            Id = 3,
                            Username = "user1",
                            Credit = 500m
                        },
                        new
                        {
                            Id = 4,
                            Username = "user2",
                            Credit = 300m
                        },
                        new
                        {
                            Id = 5,
                            Username = "user3",
                            Credit = 200m
                        });
                });

            modelBuilder.Entity("Roulette.Domain.Entities.BetEntity", b =>
                {
                    b.HasOne("Roulette.Domain.Entities.GamblerEntity", "Gambler")
                        .WithMany("Bets")
                        .HasForeignKey("GamblerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Roulette.Domain.Entities.RouletteEntity", "Roulette")
                        .WithMany("Bets")
                        .HasForeignKey("RouletteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gambler");

                    b.Navigation("Roulette");
                });

            modelBuilder.Entity("Roulette.Domain.Entities.CrupierEntity", b =>
                {
                    b.HasOne("Roulette.Domain.Entities.UserEntity", null)
                        .WithOne()
                        .HasForeignKey("Roulette.Domain.Entities.CrupierEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Roulette.Domain.Entities.GamblerEntity", b =>
                {
                    b.HasOne("Roulette.Domain.Entities.UserEntity", null)
                        .WithOne()
                        .HasForeignKey("Roulette.Domain.Entities.GamblerEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Roulette.Domain.Entities.RouletteEntity", b =>
                {
                    b.Navigation("Bets");
                });

            modelBuilder.Entity("Roulette.Domain.Entities.GamblerEntity", b =>
                {
                    b.Navigation("Bets");
                });
#pragma warning restore 612, 618
        }
    }
}
