services:
  roulette.api:
    build:
      context: .
      dockerfile: Roulette.API/Dockerfile
    container_name: roulette.api
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - roulette_data:/app/data
      - roulette_logs:/app/logs
      - dataprotection-keys:/app/DataProtection-Keys
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/swagger || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  roulette_data:
  roulette_logs:
  redis_data:
  dataprotection-keys: